version: '3.8'

services:
  loki:
    image: grafana/loki
    container_name: loki_container
    volumes:
      - ./config/loki/loki.yml:/etc/loki/loki.yml
      - loki_data:/data
    command: -config.file=/etc/loki/loki.yml 
    networks:
      - monitoring_network
    ports:
      - 3100:3100

  promtail:
    image: grafana/promtail:latest
    container_name: promtail_container
    restart: always
    volumes:
      - /var/lib/docker/containers/:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/promtail/promtail.yml:/etc/promtail/promtail.yml
      - promtail_data:/data/promtail
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - monitoring_network

volumes:
  promtail_data:
  loki_data:

networks:
  monitoring_network: