version: '3.8'

services:

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring_network
    ports:
      - 60000:3000

  loki:
    image: grafana/loki:latest
    container_name: loki_container
    user: root
    volumes:
      - ./config/loki/loki.yml:/etc/loki/loki.yml
      - loki_data:/data/loki
    command: -config.file=/etc/loki/loki.yml 
    networks:
      - monitoring_network
    ports:
      - 3100:3100

  promtail:
    image: grafana/promtail:latest
    container_name: promtail_container
    user: root
    restart: always
    volumes:
      - /var/lib/docker/containers/:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/promtail/promtail.yml:/etc/promtail/promtail.yml
      - promtail_data:/data/promtail
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - monitoring_network

volumes:
  grafana_data:
  promtail_data:
  loki_data:

networks:
  monitoring_network: