server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /data/promtail/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # This rule finds the log file path
      - source_labels: ['__meta_docker_container_id']
        target_label: '__path__'
        replacement: '/var/lib/docker/containers/$1/$1-json.log'
      
      # This rule adds the container name as a label
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
        replacement: '$1'
        
      # FIX 3: Add the replacement line here
      - source_labels: ['__meta_docker_container_label_service']
        target_label: 'service'
        replacement: '$1'